package com.andara.erp.dto.penawaran;

import jakarta.validation.Valid;
import jakarta.validation.constraints.NotEmpty;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

public class CreatePenawaranRequest {

    @NotNull(message = "Customer wajib dipilih")
    private Long customerId;

    private String number; // Optional: If empty, auto-generated by NumberingService

    private LocalDate date; // Optional: defaults to now

    private String notes;

    private String terms;

    @NotEmpty(message = "Penawaran harus memiliki minimal 1 item detail")
    @Valid
    private List<CreatePenawaranDetailRequest> items = new ArrayList<>();

    public CreatePenawaranRequest() {
    }

    public Long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public String getTerms() {
        return terms;
    }

    public void setTerms(String terms) {
        this.terms = terms;
    }

    public List<CreatePenawaranDetailRequest> getItems() {
        return items;
    }

    public void setItems(List<CreatePenawaranDetailRequest> items) {
        this.items = items;
    }
}
